import { Controller } from "@hotwired/stimulus"

// Handles live preview and drag-and-drop for file/image upload inputs.
//
// Usage (generated by the `upload_field` Rails helper):
//   data-controller="file-preview"
//   data-file-preview-type-value="image"  (or "file" for non-image uploads)
//
// Targets:
//   input            – the <input type="file"> (visually hidden)
//   dropzone         – the styled drag-and-drop area
//   previewContainer – wrapper shown/hidden based on selection
//   preview          – <img> element updated with the selected image (image type only)
//   filename         – element whose textContent is set to the selected filename

export default class extends Controller {
  static targets = ["input", "dropzone", "placeholder", "previewContainer", "preview", "filename"]
  static values  = { type: { type: String, default: "image" } }

  // Open the native file picker when the drop zone is clicked or keyboard-activated
  openPicker() {
    if (this._justDropped) return   // suppress the synthetic click fired after a drop
    this.inputTarget.click()
  }

  // Highlight the drop zone while a file is dragged over it
  dragover(event) {
    event.preventDefault()
    this.dropzoneTarget.dataset.dragging = ""
  }

  // Remove highlight when the drag leaves the drop zone entirely
  dragleave(event) {
    if (!this.dropzoneTarget.contains(event.relatedTarget)) {
      delete this.dropzoneTarget.dataset.dragging
    }
  }

  // Handle a file dropped onto the drop zone
  drop(event) {
    event.preventDefault()
    delete this.dropzoneTarget.dataset.dragging

    // Flag to suppress the spurious click event some browsers fire after a drop
    this._justDropped = true
    requestAnimationFrame(() => { this._justDropped = false })

    const files = event.dataTransfer.files
    if (!files.length) return

    // Sync the dropped file into the native input so the form submits it
    try {
      const dt = new DataTransfer()
      dt.items.add(files[0])
      this.inputTarget.files = dt.files
    } catch (_) { /* DataTransfer not supported in this browser */ }

    this._processFile(files[0])
  }

  // Handle file selected via the native picker
  update() {
    const file = this.inputTarget.files[0]
    if (!file) {
      this.previewContainerTarget.classList.add("hidden")
      if (this.hasPlaceholderTarget) this.placeholderTarget.classList.remove("hidden")
      return
    }
    this._processFile(file)
  }

  // ── Private ─────────────────────────────────────────────────────────────

  _processFile(file) {
    // Uncheck any "remove" checkbox when a new file is picked
    this.element.querySelectorAll('input[type="checkbox"]').forEach(cb => { cb.checked = false })

    // Swap placeholder ↔ preview inside the drop zone
    if (this.hasPlaceholderTarget) this.placeholderTarget.classList.add("hidden")
    this.previewContainerTarget.classList.remove("hidden")

    if (this.typeValue === "image") {
      const reader = new FileReader()
      reader.onload = (e) => {
        if (this.hasPreviewTarget)  this.previewTarget.src = e.target.result
        if (this.hasFilenameTarget) this.filenameTarget.textContent = file.name
      }
      reader.readAsDataURL(file)
    } else {
      if (this.hasFilenameTarget) this.filenameTarget.textContent = file.name
    }
  }
}
