version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  # Rails 7.2's activesupport depends on minitest >= 5.1, < 6.
  - dependency-name: minitest
    update-types:
    - version-update:semver-major
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
